project_id = "vabopanfmosvglgqyxco"
VITE_SUPABASE_PUBLISHABLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnb3JmaWRrdG55emF5bWxuZG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxMDEzNTgsImV4cCI6MjA5MDY3NzM1OH0.1RaPLYwsbXzAafjoHh4MqWc1cWXGNhho130_9imrlOQ"
VITE_SUPABASE_URL="https://agorfidktnyzaymlndmz.supabase.co"