-- 10. NEW PRODUCT MIGRATION (p389-p435)
-- Adding 47 new products to the TofhaVerse catalog.
-- Following the user request for range 389 to 435.

INSERT INTO public.products (name, slug, price, category_name, category_id, short_desc, description, images, stock, rating, review_count, is_best_seller, is_new_arrival, occasion, recipient, vibe, details)
VALUES
   
    ('Artisan Piece P397', 'p397', 155.00, 'Home & Ambiance', (SELECT id FROM public.categories WHERE name = 'Home & Ambiance' LIMIT 1), 'Hand-forged iron candelabra.', 'A centerpiece that commands attention with its raw, industrial elegance.', ARRAY['product-images/p397.jpg'], 12, 4.9, 14, false, true, ARRAY['new home', 'wedding'], ARRAY['for home'], ARRAY['industrial', 'elegant'], ARRAY['Wrought iron', 'Hand-finished']),
    ('Artisan Piece P398', 'p398', 72.00, 'Gourmet & Sweets', (SELECT id FROM public.categories WHERE name = 'Gourmet & Sweets' LIMIT 1), 'Artisan chocolate truffle set.', 'Hand-painted truffles filled with exotic infusions like hibiscus and sea salt.', ARRAY['product-images/p398.jpg'], 55, 5.0, 38, true, true, ARRAY['birthday', 'anniversary'], ARRAY['for foodies'], ARRAY['decadent', 'sweet'], ARRAY['70% Dark chocolate', 'Hand-painted']),
    ('Artisan Piece P399', 'p399', 185.00, 'Jewelry & Accessories', (SELECT id FROM public.categories WHERE name = 'Jewelry & Accessories' LIMIT 1), 'Signature leather folio.', 'Meticulously crafted from full-grain leather for the modern professional.', ARRAY['product-images/p399.jpg'], 20, 4.8, 22, false, true, ARRAY['graduation', 'promotion'], ARRAY['for professionals'], ARRAY['professional', 'sleek'], ARRAY['Full-grain leather', 'Stitched by hand']),
    ('Artisan Piece P400', 'p400', 58.00, 'Plants & Green Living', (SELECT id FROM public.categories WHERE name = 'Plants & Green Living' LIMIT 1), 'Tabletop terrarium kit.', 'Everything needed to build a self-sustaining miniature forest at your desk.', ARRAY['product-images/p400.jpg'], 45, 4.7, 85, false, true, ARRAY['just because', 'new home'], ARRAY['for nature lovers'], ARRAY['zen', 'green'], ARRAY['Recycled glass', 'Moss included']),
    ('Artisan Piece P401', 'p401', 120.00, 'Bath & Wellness', (SELECT id FROM public.categories WHERE name = 'Bath & Wellness' LIMIT 1), 'Botanical skin ritual set.', 'A curated collection of organic oils and salts for a spa-like experience.', ARRAY['product-images/p401.jpg'], 30, 4.9, 29, false, true, ARRAY['self care', 'birthday'], ARRAY['for her'], ARRAY['luminous', 'soothing'], ARRAY['Cold-pressed oils', 'Organic salts']),
    ('Artisan Piece P402', 'p402', 48.00, 'Stationery & Books', (SELECT id FROM public.categories WHERE name = 'Stationery & Books' LIMIT 1), 'Hand-bound linen journal.', 'Acid-free paper wrapped in premium linen, designed for a lifetime of thoughts.', ARRAY['product-images/p402.jpg'], 100, 4.8, 64, false, true, ARRAY['birthday', 'graduation'], ARRAY['for writers'], ARRAY['classic', 'tactile'], ARRAY['100% Linen cover', 'Lay-flat binding']),
    ('Artisan Piece P403', 'p403', 165.00, 'Home & Ambiance', (SELECT id FROM public.categories WHERE name = 'Home & Ambiance' LIMIT 1), 'Milled brass wall clock.', 'A minimalist statement piece that explores the beauty of geometric precision.', ARRAY['product-images/p403.jpg'], 15, 5.0, 11, true, true, ARRAY['new home', 'wedding'], ARRAY['for home'], ARRAY['minimalist', 'precise'], ARRAY['Solid brass', 'Silent movement']),
    ('Artisan Piece P404', 'p404', 85.00, 'Gourmet & Sweets', (SELECT id FROM public.categories WHERE name = 'Gourmet & Sweets' LIMIT 1), 'Artisan olive oil collection.', 'Three different regional oils showcasing the diverse flavors of the harvest.', ARRAY['product-images/p404.jpg'], 40, 4.9, 52, false, true, ARRAY['holiday', 'new home'], ARRAY['for chefs'], ARRAY['sophisticated', 'rich'], ARRAY['Extra virgin', 'Cold-pressed']),
    ('Artisan Piece P405', 'p405', 210.00, 'Jewelry & Accessories', (SELECT id FROM public.categories WHERE name = 'Jewelry & Accessories' LIMIT 1), 'Forged silver cuff links.', 'Industrial elegance for the modern gentleman, hand-finished in our studio.', ARRAY['product-images/p405.jpg'], 10, 5.0, 9, false, true, ARRAY['wedding', 'promotion'], ARRAY['for him'], ARRAY['elegant', 'solid'], ARRAY['925 Sterling silver', 'Oxidized finish']),
    ('Artisan Piece P406', 'p406', 42.00, 'Plants & Green Living', (SELECT id FROM public.categories WHERE name = 'Plants & Green Living' LIMIT 1), 'Miniature cactus garden.', 'Low-maintenance desert icons house in a modern geometric ceramic pot.', ARRAY['product-images/p406.jpg'], 70, 4.6, 41, false, true, ARRAY['just because', 'earth day'], ARRAY['for coworkers'], ARRAY['clean', 'rugged'], ARRAY['Hand-painted pot', 'Rare varieties']),
    ('Artisan Piece P407', 'p407', 135.00, 'Bath & Wellness', (SELECT id FROM public.categories WHERE name = 'Bath & Wellness' LIMIT 1), 'Ethereal bath bomb set.', 'Hand-pressed with organic botanicals for a luxurious and colorful soak.', ARRAY['product-images/p407.jpg'], 50, 4.8, 67, false, true, ARRAY['self care', 'birthday'], ARRAY['for relaxation'], ARRAY['vibrant', 'floral'], ARRAY['Organic essential oils', 'Vegan friendly']),
    ('Artisan Piece P408', 'p408', 35.00, 'Stationery & Books', (SELECT id FROM public.categories WHERE name = 'Stationery & Books' LIMIT 1), 'Letterpress card collection.', 'Intricate designs pressed into thick cotton paper for your most important messages.', ARRAY['product-images/p408.jpg'], 200, 4.7, 89, false, true, ARRAY['anniversary', 'just because'], ARRAY['for family'], ARRAY['delicate', 'classic'], ARRAY['Cotton paper', 'Hand-mixed ink']),
    ('Artisan Piece P409', 'p409', 195.00, 'Home & Ambiance', (SELECT id FROM public.categories WHERE name = 'Home & Ambiance' LIMIT 1), 'Hand-woven sisal rug.', 'A durable and textured piece that brings a natural, grounded feel to any room.', ARRAY['product-images/p409.jpg'], 8, 4.9, 15, false, true, ARRAY['new home', 'anniversary'], ARRAY['for home'], ARRAY['natural', 'textured'], ARRAY['Sustainable sisal', 'Hand-woven']),
    ('Artisan Piece P410', 'p410', 65.00, 'Gourmet & Sweets', (SELECT id FROM public.categories WHERE name = 'Gourmet & Sweets' LIMIT 1), 'Artisan honey flight.', 'A selection of rare, single-origin honeys from protected wildflower meadows.', ARRAY['product-images/p410.jpg'], 60, 5.0, 33, true, true, ARRAY['holiday', 'birthday'], ARRAY['for gourmets'], ARRAY['rich', 'sweet'], ARRAY['Unfiltered', 'Raw']),
    ('Artisan Piece P411', 'p411', 280.00, 'Jewelry & Accessories', (SELECT id FROM public.categories WHERE name = 'Jewelry & Accessories' LIMIT 1), 'Bespoke silver locket.', 'A timeless heirloom piece, meticulously crafted to hold your most precious secrets.', ARRAY['product-images/p411.jpg'], 5, 5.0, 7, false, true, ARRAY['anniversary', 'wedding'], ARRAY['for her'], ARRAY['romantic', 'heritage'], ARRAY['Sterling silver', 'Engraving possible']),
    ('Artisan Piece P412', 'p412', 55.00, 'Plants & Green Living', (SELECT id FROM public.categories WHERE name = 'Plants & Green Living' LIMIT 1), 'Self-watering herb planter.', 'Modern design meets functional gardening for the sustainable urban chef.', ARRAY['product-images/p412.jpg'], 90, 4.8, 52, false, true, ARRAY['new home', 'promotion'], ARRAY['for foodies'], ARRAY['efficient', 'green'], ARRAY['Recycled plastic', 'Wick system']),
    ('Artisan Piece P413', 'p413', 145.00, 'Bath & Wellness', (SELECT id FROM public.categories WHERE name = 'Bath & Wellness' LIMIT 1), 'Signature aromatherapy diffuser.', 'A sculptural ceramic diffuser that brings peace and tranquility to your space.', ARRAY['product-images/p413.jpg'], 25, 4.9, 44, true, true, ARRAY['self care', 'new home'], ARRAY['for relaxation'], ARRAY['zen', 'elegant'], ARRAY['Kiln-fired ceramic', 'Ultrasonic technology']),
    ('Artisan Piece P414', 'p414', 44.00, 'Stationery & Books', (SELECT id FROM public.categories WHERE name = 'Stationery & Books' LIMIT 1), 'Minimalist desktop planner.', 'Focus your intentions and organize your days with this clean, artisan-made pad.', ARRAY['product-images/p414.jpg'], 120, 4.7, 76, false, true, ARRAY['new year', 'back to school'], ARRAY['for professionals'], ARRAY['ordered', 'clean'], ARRAY['70lb paper', 'Glue bound']),
    ('Artisan Piece P415', 'p415', 175.00, 'Home & Ambiance', (SELECT id FROM public.categories WHERE name = 'Home & Ambiance' LIMIT 1), 'Hand-carved marble bowl.', 'Carved from a single block of Carrara marble, celebrating the natural stone grain.', ARRAY['product-images/p415.jpg'], 10, 5.0, 12, false, true, ARRAY['wedding', 'new home'], ARRAY['for home'], ARRAY['luxurious', 'solid'], ARRAY['Carrara marble', 'Hand-polished']),
    ('Artisan Piece P416', 'p416', 92.00, 'Gourmet & Sweets', (SELECT id FROM public.categories WHERE name = 'Gourmet & Sweets' LIMIT 1), 'Artisan coffee sampler.', 'A collection of four rare, single-origin roasts for the coffee connoisseur.', ARRAY['product-images/p416.jpg'], 40, 4.9, 58, false, true, ARRAY['birthday', 'holiday'], ARRAY['for enthusiasts'], ARRAY['bold', 'vibrant'], ARRAY['Small-batch roasted', 'Sustainable bags']),
    ('Artisan Piece P417', 'p417', 225.00, 'Jewelry & Accessories', (SELECT id FROM public.categories WHERE name = 'Jewelry & Accessories' LIMIT 1), 'Milled titanium ring.', 'A minimalist band exploring the strength and lightness of modern metals.', ARRAY['product-images/p417.jpg'], 15, 5.0, 8, true, true, ARRAY['anniversary', 'wedding'], ARRAY['for him'], ARRAY['modern', 'strong'], ARRAY['Grade 5 Titanium', 'Precision milled']),
    ('Artisan Piece P418', 'p418', 38.00, 'Plants & Green Living', (SELECT id FROM public.categories WHERE name = 'Plants & Green Living' LIMIT 1), 'Desktop air plant home.', 'A minimalist brass and glass structure designed to highlight botanical form.', ARRAY['product-images/p418.jpg'], 100, 4.7, 39, false, true, ARRAY['just because', 'earth day'], ARRAY['for coworkers'], ARRAY['airy', 'clean'], ARRAY['Solid brass', 'Hand-cut glass']),
    ('Artisan Piece P419', 'p419', 115.00, 'Bath & Wellness', (SELECT id FROM public.categories WHERE name = 'Bath & Wellness' LIMIT 1), 'Nocturnal renewal face oil.', 'A potent botanical blend designed to revitalize your skin during sleep.', ARRAY['product-images/p419.jpg'], 30, 4.9, 41, false, true, ARRAY['self care', 'birthday'], ARRAY['for rejuvenation'], ARRAY['luminous', 'potent'], ARRAY['Blue Tansy', 'Rosehip oil']),
    ('Artisan Piece P420', 'p420', 52.00, 'Stationery & Books', (SELECT id FROM public.categories WHERE name = 'Stationery & Books' LIMIT 1), 'Limited edition sketchbook.', 'Heavyweight paper and a durable cloth cover for your most ambitious sketches.', ARRAY['product-images/p420.jpg'], 80, 4.8, 54, false, true, ARRAY['birthday', 'graduation'], ARRAY['for artists'], ARRAY['rugged', 'tactile'], ARRAY['140gsm paper', 'Cloth bound']),
    ('Artisan Piece P421', 'p421', 195.00, 'Home & Ambiance', (SELECT id FROM public.categories WHERE name = 'Home & Ambiance' LIMIT 1), 'Hand-forged brass tray.', 'A versatile and elegant piece that brings a warm, metallic glow to your home.', ARRAY['product-images/p421.jpg'], 12, 5.0, 14, true, true, ARRAY['new home', 'wedding'], ARRAY['for home'], ARRAY['vibrant', 'warm'], ARRAY['Milled brass', 'Polished finish']),
    ('Artisan Piece P422', 'p422', 78.00, 'Gourmet & Sweets', (SELECT id FROM public.categories WHERE name = 'Gourmet & Sweets' LIMIT 1), 'Artisan jam quartet.', 'Four seasonal preserves made with wild berries and traditional methods.', ARRAY['product-images/p422.jpg'], 50, 4.8, 27, false, true, ARRAY['holiday', 'new home'], ARRAY['for family'], ARRAY['vibrant', 'sweet'], ARRAY['Wild harvested', 'Low sugar']),
    ('Artisan Piece P423', 'p423', 245.00, 'Jewelry & Accessories', (SELECT id FROM public.categories WHERE name = 'Jewelry & Accessories' LIMIT 1), 'Signature leather backpack.', 'The ultimate urban explorer bag, hand-built for a lifetime of adventure.', ARRAY['product-images/p423.jpg'], 8, 4.9, 12, false, true, ARRAY['graduation', 'promotion'], ARRAY['for adventurers'], ARRAY['rugged', 'sophisticated'], ARRAY['Full-grain leather', 'Solid brass hardware']),
    ('Artisan Piece P424', 'p424', 64.00, 'Plants & Green Living', (SELECT id FROM public.categories WHERE name = 'Plants & Green Living' LIMIT 1), 'Succulent garden set.', 'A curated selection of rare succulents in a hand-crafted wooden box.', ARRAY['product-images/p424.jpg'], 40, 4.7, 45, false, true, ARRAY['birthday', 'just because'], ARRAY['for nature lovers'], ARRAY['zen', 'structured'], ARRAY['Reclaimed wood', 'Sustainable soil']),
    ('Artisan Piece P425', 'p425', 135.00, 'Bath & Wellness', (SELECT id FROM public.categories WHERE name = 'Bath & Wellness' LIMIT 1), 'Botanical fragrance flight.', 'Discover your signature scent with this collection of nature-inspired oils.', ARRAY['product-images/p425.jpg'], 35, 4.9, 32, false, true, ARRAY['birthday', 'anniversary'], ARRAY['for her'], ARRAY['ethereal', 'complex'], ARRAY['Natural oils', 'Vegan base']),
    ('Artisan Piece P426', 'p426', 42.00, 'Stationery & Books', (SELECT id FROM public.categories WHERE name = 'Stationery & Books' LIMIT 1), 'Hand-stitched leather notebook.', 'A rugged and tactile companion for your thoughts, dreams, and discoveries.', ARRAY['product-images/p426.jpg'], 100, 4.8, 63, false, true, ARRAY['new year', 'graduation'], ARRAY['for explorers'], ARRAY['rugged', 'classic'], ARRAY['Top-grain leather', 'Refillable']),
    ('Artisan Piece P427', 'p427', 165.00, 'Home & Ambiance', (SELECT id FROM public.categories WHERE name = 'Home & Ambiance' LIMIT 1), 'Sculptural stone candle holder.', 'Carved from river stone, bringing the weight and peace of nature indoors.', ARRAY['product-images/p427.jpg'], 18, 5.0, 9, true, true, ARRAY['new home', 'wedding'], ARRAY['for home'], ARRAY['monumental', 'grounded'], ARRAY['Natural stone', 'Hand-finished']),
    ('Artisan Piece P428', 'p428', 88.00, 'Gourmet & Sweets', (SELECT id FROM public.categories WHERE name = 'Gourmet & Sweets' LIMIT 1), 'Artisan vinegar trio.', 'Aged in oak barrels, infused with botanical extracts for complex flavor.', ARRAY['product-images/p428.jpg'], 45, 4.9, 24, false, true, ARRAY['holiday', 'birthday'], ARRAY['for chefs'], ARRAY['sophisticated', 'refined'], ARRAY['Oak aged', 'Non-GMO']),
    ('Artisan Piece P429', 'p429', 215.00, 'Jewelry & Accessories', (SELECT id FROM public.categories WHERE name = 'Jewelry & Accessories' LIMIT 1), 'Industrial silver chain.', 'A bold, hand-linked piece that explores the beauty of raw metal forms.', ARRAY['product-images/p429.jpg'], 12, 5.0, 11, false, true, ARRAY['anniversary', 'birthday'], ARRAY['for him'], ARRAY['bold', 'industrial'], ARRAY['925 Sterling', 'High polish']),
    ('Artisan Piece P430', 'p430', 48.00, 'Plants & Green Living', (SELECT id FROM public.categories WHERE name = 'Plants & Green Living' LIMIT 1), 'Miniature bonsai kit.', 'Start your journey into the ancient art of bonsai with this complete set.', ARRAY['product-images/p430.jpg'], 50, 4.7, 88, false, true, ARRAY['birthday', 'just because'], ARRAY['for nature lovers'], ARRAY['zen', 'peaceful'], ARRAY['Juniper seed', 'Ceramic pot']),
    ('Artisan Piece P431', 'p431', 125.00, 'Bath & Wellness', (SELECT id FROM public.categories WHERE name = 'Bath & Wellness' LIMIT 1), 'Luminous bath salt ritual.', 'Natural salts infused with flowers and oils for a revitalizing soak.', ARRAY['product-images/p431.jpg'], 60, 4.9, 52, false, true, ARRAY['self care', 'birthday'], ARRAY['for rejuvenation'], ARRAY['luminous', 'vibrant'], ARRAY['Dead Sea salt', 'Dried flowers']),
    ('Artisan Piece P432', 'p432', 38.00, 'Stationery & Books', (SELECT id FROM public.categories WHERE name = 'Stationery & Books' LIMIT 1), 'Letterpress correspondence set.', 'Elegant cards and envelopes for your most important handwritten notes.', ARRAY['product-images/p432.jpg'], 150, 4.8, 41, false, true, ARRAY['anniversary', 'just because'], ARRAY['for family'], ARRAY['delicate', 'natural'], ARRAY['Cotton paper', 'Letterpress']),
    ('Artisan Piece P433', 'p433', 155.00, 'Home & Ambiance', (SELECT id FROM public.categories WHERE name = 'Home & Ambiance' LIMIT 1), 'Hand-woven wool throw.', 'A warm and textured piece, woven using traditional heritage techniques.', ARRAY['product-images/p433.jpg'], 15, 5.0, 18, true, true, ARRAY['new home', 'winter holiday'], ARRAY['for home'], ARRAY['textured', 'warm'], ARRAY['100% Merino wool', 'Ethically sourced']),
    ('Artisan Piece P434', 'p434', 85.00, 'Gourmet & Sweets', (SELECT id FROM public.categories WHERE name = 'Gourmet & Sweets' LIMIT 1), 'Artisan spice sampler.', 'A collection of eight whole spices from protected heritage gardens.', ARRAY['product-images/p434.jpg'], 40, 4.9, 36, false, true, ARRAY['birthday', 'holiday'], ARRAY['for chefs'], ARRAY['bold', 'vibrant'], ARRAY['Whole spices', 'Glass jars']),
    ('Artisan Piece P435', 'p435', 320.00, 'Jewelry & Accessories', (SELECT id FROM public.categories WHERE name = 'Jewelry & Accessories' LIMIT 1), 'Elite gold artisan bracelet.', 'A heavy, hand-cast piece that celebrates the raw beauty of solid gold.', ARRAY['product-images/p435.jpg'], 3, 5.0, 5, true, true, ARRAY['anniversary', 'wedding'], ARRAY['for her'], ARRAY['luxurious', 'raw'], ARRAY['Solid 18k gold', 'One-of-a-kind'])
ON CONFLICT (slug) DO NOTHING;
